### ISSUE TITLE
Infinite loop interract with Water Barrel in Durotar blowing my logs

### ISSUE THREAD

**Issue by nahhets** [EchoTiger/NewQuestingPack#42]
http://www.wowhead.com/object=3658/water-barrel

![screenshot_1](https://user-images.githubusercontent.com/12803617/26888936-35b49514-4bb5-11e7-854f-86a9544da3d8.png)

> [15:35:35.003 D] Exception was thrown in BotBase.Root.Tick
[15:35:35.003 D] Buddy.Coroutines.CoroutineUnhandledException: Exception was thrown by coroutine ---> Buddy.Coroutines.CoroutineUnhandledException: Exception was thrown by coroutine ---> System.InvalidOperationException: Cannot call Location on an invalid object.
   at Styx.WoWInternals.WoWObjects.WoWObject.EnsureValid(String funcName)
   at Styx.WoWInternals.WoWObjects.WoWGameObject.‌⁮⁮​‍‌⁫‌⁬‍‏⁪⁮‏‬‮‌‏‌‪⁯‏‭‏‭‭‫⁫⁮‬‪⁮‌​‏⁫‌‌⁪‬‮()
   at Styx.Helpers.PerFrameCachedValue`1.get_Value()
   at Styx.WoWInternals.WoWObjects.WoWGameObject.get_Location()
   at Styx.WoWInternals.WoWObjects.WoWObject.‬⁮‎‍‪⁫​‮‭⁪⁪⁪​⁪‬​‫​‌‎‪‭‫⁮⁪‏‪⁬‍‏‭‏⁮‫‫‪‫​‍‏‮()
   at Styx.Helpers.TimeCachedValue`1.Refreshed()
   at Styx.Helpers.TimeCachedValue`1.get_Value()
   at Styx.WoWInternals.WoWObjects.WoWObject.get_InLineOfSight()
   at __CompileBatchNamespace10__.__CompiledBatchClass__.<TreasureHunter>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at __CompileBatchNamespace10__.__CompiledBatchClass__.<FunctionPulser>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommonBehaviors.Actions.ActionRunCoroutine. C$\]J$T"?4C2KS@dBeXv9j0L%.@/RaMRf)bIY~\\!-euyM}2HVn.MoveNext()
   --- End of inner exception stack trace ---
   at Buddy.Coroutines.Coroutine.⁭‏‎⁬⁮⁬⁬⁯‪⁬⁬⁭‌⁫⁬‫‭‫‏⁪‭‎⁯‍⁯‎⁬⁭⁪‬‭‪‭‮‭‮‎‭⁮‮(Boolean )
   at Buddy.Coroutines.Coroutine.‍‏⁯⁫‍‎⁫⁬‬‍⁭⁭​⁫⁭⁭‬‫‎⁪‭‪‏‌‍‍⁭‌‎⁭⁬‪‮⁪‮⁭‏⁮‪⁪‮(Boolean )
   at Buddy.Coroutines.Coroutine.Resume()
   at CommonBehaviors.Actions.ActionRunCoroutine.Run(Object context)
   at Styx.TreeSharp.Action.RunAction(Object context)
   at Styx.TreeSharp.Action.Bq0I8)bO\*:M'j~3SQ'p7Iz\&"!.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.TreeSharp.PrioritySelector.zY'X|M(9TD\&_F=mU!OLOj\]\&P#.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.Common.HookExecutor.Run(Object context)
   at Styx.TreeSharp.Action.RunAction(Object context)
   at Styx.TreeSharp.Action.Bq0I8)bO\*:M'j~3SQ'p7Iz\&"!.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.CommonBot.Coroutines.CoroutineCompositeExtensions.B"?2/xx0x \[JV\&/\.i\]<x/J?}.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at -\&"K'eRq#}a\&q>TF\&RiBA#4O).05_$J/\*#)mp0NaEC# <2_(Sa#.<J'Y\\N0UNV} N1y\*7-VcTRE{!.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Styx.CommonBot.TreeRoot.3I=w\*qJ??T>Y'a(})2xxy)sr\..ciQ%wn?!)_)0/5~A0YZ#_X9K\&.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommonBehaviors.Actions.ActionRunCoroutine. C$\]J$T"?4C2KS@dBeXv9j0L%.@/RaMRf)bIY~\\!-euyM}2HVn.MoveNext()
   --- End of inner exception stack trace ---
   at Buddy.Coroutines.Coroutine.⁭‏‎⁬⁮⁬⁬⁯‪⁬⁬⁭‌⁫⁬‫‭‫‏⁪‭‎⁯‍⁯‎⁬⁭⁪‬‭‪‭‮‭‮‎‭⁮‮(Boolean )
   at Buddy.Coroutines.Coroutine.‍‏⁯⁫‍‎⁫⁬‬‍⁭⁭​⁫⁭⁭‬‫‎⁪‭‪‏‌‍‍⁭‌‎⁭⁬‪‮⁪‮⁭‏⁮‪⁪‮(Boolean )
   at Buddy.Coroutines.Coroutine.Resume()
   at CommonBehaviors.Actions.ActionRunCoroutine.Run(Object context)
   at Styx.TreeSharp.Action.RunAction(Object context)
   at Styx.TreeSharp.Action.Bq0I8)bO\*:M'j~3SQ'p7Iz\&"!.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.TreeSharp.PrioritySelector.zY'X|M(9TD\&_F=mU!OLOj\]\&P#.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.Common.HookExecutor.Run(Object context)
   at Styx.TreeSharp.Action.RunAction(Object context)
   at Styx.TreeSharp.Action.Bq0I8)bO\*:M'j~3SQ'p7Iz\&"!.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.CommonBot.TreeRoot.3I=w\*qJ??T>Y'a(})2xxy)sr\..⁬‫‬‭‬⁯‌⁭‮⁮‏‌‭⁭‍‪‮‮‭⁭‍⁯‌‭‭⁭⁭‎‭‬‮⁬‪​‏‬‌​⁯⁮‮()
   at Styx.CommonBot.TreeRoot.‎⁯‏‮⁭‍‪‪​⁪‬‏‫‫⁮⁬‍‏⁭⁬‌‎⁬‎⁪⁮⁪‎‪‪⁭⁭⁫⁪‪‌⁬​‏‮(Action , String , Boolean )
[15:35:35.095 D] Exception was thrown in BotBase.Root.Tick
[15:35:35.096 D] Buddy.Coroutines.CoroutineUnhandledException: Exception was thrown by coroutine ---> Buddy.Coroutines.CoroutineUnhandledException: Exception was thrown by coroutine ---> System.InvalidOperationException: Cannot call Location on an invalid object.
   at Styx.WoWInternals.WoWObjects.WoWObject.EnsureValid(String funcName)
   at Styx.WoWInternals.WoWObjects.WoWGameObject.‌⁮⁮​‍‌⁫‌⁬‍‏⁪⁮‏‬‮‌‏‌‪⁯‏‭‏‭‭‫⁫⁮‬‪⁮‌​‏⁫‌‌⁪‬‮()
   at Styx.Helpers.PerFrameCachedValue`1.get_Value()
   at Styx.WoWInternals.WoWObjects.WoWGameObject.get_Location()
   at Styx.WoWInternals.WoWObjects.WoWObject.‬⁮‎‍‪⁫​‮‭⁪⁪⁪​⁪‬​‫​‌‎‪‭‫⁮⁪‏‪⁬‍‏‭‏⁮‫‫‪‫​‍‏‮()
   at Styx.Helpers.TimeCachedValue`1.Refreshed()
   at Styx.Helpers.TimeCachedValue`1.get_Value()
   at Styx.WoWInternals.WoWObjects.WoWObject.get_InLineOfSight()
   at __CompileBatchNamespace10__.__CompiledBatchClass__.<TreasureHunter>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at __CompileBatchNamespace10__.__CompiledBatchClass__.<FunctionPulser>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommonBehaviors.Actions.ActionRunCoroutine. C$\]J$T"?4C2KS@dBeXv9j0L%.@/RaMRf)bIY~\\!-euyM}2HVn.MoveNext()
   --- End of inner exception stack trace ---
   at Buddy.Coroutines.Coroutine.⁭‏‎⁬⁮⁬⁬⁯‪⁬⁬⁭‌⁫⁬‫‭‫‏⁪‭‎⁯‍⁯‎⁬⁭⁪‬‭‪‭‮‭‮‎‭⁮‮(Boolean )
   at Buddy.Coroutines.Coroutine.‍‏⁯⁫‍‎⁫⁬‬‍⁭⁭​⁫⁭⁭‬‫‎⁪‭‪‏‌‍‍⁭‌‎⁭⁬‪‮⁪‮⁭‏⁮‪⁪‮(Boolean )
   at Buddy.Coroutines.Coroutine.Resume()
   at CommonBehaviors.Actions.ActionRunCoroutine.Run(Object context)
   at Styx.TreeSharp.Action.RunAction(Object context)
   at Styx.TreeSharp.Action.Bq0I8)bO\*:M'j~3SQ'p7Iz\&"!.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.TreeSharp.PrioritySelector.zY'X|M(9TD\&_F=mU!OLOj\]\&P#.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.Common.HookExecutor.Run(Object context)
   at Styx.TreeSharp.Action.RunAction(Object context)
   at Styx.TreeSharp.Action.Bq0I8)bO\*:M'j~3SQ'p7Iz\&"!.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.CommonBot.Coroutines.CoroutineCompositeExtensions.B"?2/xx0x \[JV\&/\.i\]<x/J?}.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at -\&"K'eRq#}a\&q>TF\&RiBA#4O).05_$J/\*#)mp0NaEC# <2_(Sa#.<J'Y\\N0UNV} N1y\*7-VcTRE{!.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Styx.CommonBot.TreeRoot.3I=w\*qJ??T>Y'a(})2xxy)sr\..ciQ%wn?!)_)0/5~A0YZ#_X9K\&.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommonBehaviors.Actions.ActionRunCoroutine. C$\]J$T"?4C2KS@dBeXv9j0L%.@/RaMRf)bIY~\\!-euyM}2HVn.MoveNext()
   --- End of inner exception stack trace ---
   at Buddy.Coroutines.Coroutine.⁭‏‎⁬⁮⁬⁬⁯‪⁬⁬⁭‌⁫⁬‫‭‫‏⁪‭‎⁯‍⁯‎⁬⁭⁪‬‭‪‭‮‭‮‎‭⁮‮(Boolean )
   at Buddy.Coroutines.Coroutine.‍‏⁯⁫‍‎⁫⁬‬‍⁭⁭​⁫⁭⁭‬‫‎⁪‭‪‏‌‍‍⁭‌‎⁭⁬‪‮⁪‮⁭‏⁮‪⁪‮(Boolean )
   at Buddy.Coroutines.Coroutine.Resume()
   at CommonBehaviors.Actions.ActionRunCoroutine.Run(Object context)
   at Styx.TreeSharp.Action.RunAction(Object context)
   at Styx.TreeSharp.Action.Bq0I8)bO\*:M'j~3SQ'p7Iz\&"!.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.TreeSharp.PrioritySelector.zY'X|M(9TD\&_F=mU!OLOj\]\&P#.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.Common.HookExecutor.Run(Object context)
   at Styx.TreeSharp.Action.RunAction(Object context)
   at Styx.TreeSharp.Action.Bq0I8)bO\*:M'j~3SQ'p7Iz\&"!.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.CommonBot.TreeRoot.3I=w\*qJ??T>Y'a(})2xxy)sr\..⁬‫‬‭‬⁯‌⁭‮⁮‏‌‭⁭‍‪‮‮‭⁭‍⁯‌‭‭⁭⁭‎‭‬‮⁬‪​‏‬‌​⁯⁮‮()
   at Styx.CommonBot.TreeRoot.‎⁯‏‮⁭‍‪‪​⁪‬‏‫‫⁮⁬‍‏⁭⁬‌‎⁬‎⁪⁮⁪‎‪‪⁭⁭⁫⁪‪‌⁬​‏‮(Action , String , Boolean )
[15:35:35.172 D] Exception was thrown in BotBase.Root.Tick

**Comment by nahhets** [comment]
Ive switched off "Find Treasure Chests" for fixing this. But previous (2 weeks ago) release was ok

**Comment by EchoTiger** [comment]
It was a bug in the Treasure Hook that should be fixed now.
